
consul:
  clusterSize: 3
  storageClassName:
  pvSize: 100Mi
  image:
    name: consul
    tag: 1.5.0
  serverService: consul

controller:
  image:
    name: ha-postgres-controller
    tag: 1.0.0

postgres:
  clusterSize: 3
  storageClassName:
  pvSize: 1Gi
  image:
    name: ha-postgres
    tag: 11.3
  dbName: postgres
  superuserName: postgres
  superuserPassword: su123
  replicationPassword: rep123
  masterService: postgres-master

pgbouncer:
  image: 
    name: ha-pgbouncer
    tag: 1.12.0