branches:
  only:
    - master
    - develop

dist: bionic
language: python
python:
  - "3.8"

env:
  global:
    - MINIKUBE_VERSION=1.9.2
    - K8S_VERSION=1.18.1
    - HELM_VERSION=3.1.2
    - DOCKER_VERSION=5:19.03.8~3-0

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install conntrack docker-ce=$DOCKER_VERSION~ubuntu-$(lsb_release -cs)

install:
  - ./scripts/install-minikube.sh

script:
  - POSTGRES_IMAGE_TAG=12.0 ./scripts/deploy-chart.sh seed integration-tests/chart-values.common.yaml integration-tests/chart-values.seed.yaml
  - ./scripts/deploy-chart.sh main integration-tests/chart-values.common.yaml integration-tests/chart-values.main.yaml
  - cd integration-tests; ./run.sh

after_script:
  - kubectl describe nodes
  - kubectl -n main describe pods -l 'app in (consul, ha-postgres, postgres-lb)'
  - kubectl -n main logs -l 'app in (consul, ha-postgres, postgres-lb)' --all-containers=true --prefix --tail=-1
  - kubectl -n seed describe pods -l 'app in (consul, ha-postgres, postgres-lb)'
  - kubectl -n seed logs -l 'app in (consul, ha-postgres, postgres-lb)' --all-containers=true --prefix --tail=-1