branches:
  only:
    - master
    - develop

dist: bionic
language: python
python:
  - "3.8"

env:
  global:
    - MINIKUBE_VERSION=1.7.1
    - K8S_VERSION=1.17.2
    - HELM_VERSION=3.0.3
    - DOCKER_VERSION=5:19.03.6~3-0

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce=$DOCKER_VERSION~ubuntu-$(lsb_release -cs)

install:
  - ./scripts/install-minikube.sh

script:
  - ./scripts/deploy-chart.sh chart/values.travis.yaml
  - ./scripts/run-integration-tests.sh

after_script:
  - kubectl describe nodes
  - kubectl describe pods -l 'app in (consul, ha-postgres)'
  - kubectl logs -l 'app in (consul, ha-postgres)' --all-containers=true --prefix --tail=-1