branches:
  only:
    - master
    - develop

dist: bionic
language: python
python:
  - "3.8"
  
env:
  global:
    - MINIKUBE_VERSION=1.7.1
    - K8S_VERSION=1.17.2
    - HELM_VERSION=3.0.3

install:
  - ./scripts/install-minikube.sh

script:
  - ./scripts/deploy-chart.sh chart/values.travis.yaml
  - ./scripts/run-integration-tests.sh

after_script:
  - kubectl describe nodes
  - kubectl describe pods -l 'app in (consul, ha-postgres)'
  - kubectl logs -l 'app in (consul, ha-postgres)' --all-containers=true --prefix --tail=-1