kind: ConfigMap
apiVersion: v1
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    defaults
      timeout connect {{ .Values.haproxy.timeouts.connect }}
      timeout client {{ .Values.haproxy.timeouts.read }}
      timeout server {{ .Values.haproxy.timeouts.read }}

    listen postgres
        bind *:{{ .Values.dbPort }}
        mode tcp
        option httpchk GET /controller/ready HTTP/1.1
        server postgres 127.0.0.1:5432 check port 80 fall 1 rise 1 inter {{ .Values.haproxy.checkInterval }} on-marked-down shutdown-sessions