kind: ConfigMap
apiVersion: v1
metadata:
  name: user-defined-postgres-init-scripts
data:
  settings-from-chart.sql: |
  {{- range $key, $value := .Values.db.postgres.settings }}
    {{- if kindIs "string" $value }}
    ALTER SYSTEM SET {{ $key }} = {{ $value | squote}};
    {{- else }}
    ALTER SYSTEM SET {{ $key }} = {{ $value }};
    {{- end }}
  {{- end }}
{{- if .Files.Glob "files/postgres-init-scripts/*.{sh,sql}" }}
{{ (.Files.Glob "files/postgres-init-scripts/*.{sh,sql}").AsConfig | indent 2 }}
{{- end }}