kind: Secret
apiVersion: v1
metadata:
  name: db-passwords
stringData:
  SUPER_USER: {{ .Values.db.postgres.users.su.password }}
  REPLICATION_USER: {{ .Values.db.postgres.users.replication.password }}
  {{- with .Values.db.seedDb }}
  {{- if .password }}
  SEED_DB_USER: {{ .password }}
  {{- end }}
  {{- end }}