kind: Secret
apiVersion: v1
metadata:
  name: db-passwords
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.superuserPassword }}
  REPLICATION_USER_PASSWORD: {{ .Values.postgres.replicationPassword }}
  CONTROLLER_USER_PASSWORD: {{ .Values.postgres.controllerPassword }}