kind: Secret
apiVersion: v1
metadata:
  name: db-passwords
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.users.su.password }}
  REPLICATION_USER_PASSWORD: {{ .Values.postgres.users.replication.password }}
  CONTROLLER_USER_PASSWORD: {{ .Values.postgres.users.controller.password }}