kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  clusterIP: None
  selector:
    app: ha-postgres
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.postgres.masterService }}
spec:
  type: ClusterIP
  ports:
    - name: pgbouncer
      port: 6432
    - name: postgres
      port: 5432
---
kind: Endpoints
apiVersion: v1
metadata:
  name: {{ .Values.postgres.masterService }}
