kind: ServiceAccount
apiVersion: v1
metadata:
  name: ha-postgres
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ha-postgres
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    resourceNames: ["postgres-master"]
    verbs: ["get", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ha-postgres
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ha-postgres
subjects:
  - kind: ServiceAccount
    name: ha-postgres