kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ha-postgres
spec: 
  replicas: {{ .Values.clusterSize }}
  updateStrategy:
    type: OnDelete
  selector: 
    matchLabels:
      app: ha-postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: ha-postgres
    spec:
      serviceAccountName: ha-postgres
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm: 
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: ha-postgres
      initContainers:
        - name: wait-consul-cluster
          image: {{ .Values.waitConsulCluster.image }}
          command:
            - sh
            - -cx
            - |
              while [ $(nslookup {{ .Values.consul.server.service }} 2> /dev/null | grep -c "Address [0-9]:") -ne {{ .Values.consul.server.clusterSize }} ]; do
                sleep 3s
              done 
          resources:
            limits:
              cpu: {{ .Values.waitConsulCluster.limits.cpu }}
              memory: {{ .Values.waitConsulCluster.limits.memory }}
      volumes:
        - name: shared
          emptyDir: {}
        - name: haproxy-config
          configMap:
            name: haproxy-config
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: shared
              mountPath: /shared
          env:
            - name: POSTGRES_DB
              value: {{ .Values.dbName }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.users.su.name }}
            - name: POSTGRES_MASTER_HOST
              value: {{ .Values.masterService }}
            - name: POSTGRES_MASTER_PORT
              value: {{ .Values.dbPort | quote }}
            - name: CONTROLLER_MANAGEMENT_PORT
              value: "80"
            - name: PROMOTE_TRIGGER_FILE
              value: /shared/promote
          envFrom:
            - secretRef:
                name: db-passwords
          resources:
            limits:
              cpu: {{ .Values.postgres.limits.cpu }}
              memory: {{ .Values.postgres.limits.memory }}
        - name: consul
          image: {{ .Values.consul.image }}
          args: ["agent", "-retry-join", {{ .Values.consul.server.service | quote }}]
          resources:
            limits:
              cpu: {{ .Values.consul.client.limits.cpu }}
              memory: {{ .Values.consul.client.limits.memory }}
        - name: haproxy
          image: {{ .Values.haproxy.image }}
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy
          ports:
            - name: tcp
              containerPort: {{ .Values.dbPort }}
          resources:
            limits:
              cpu: {{ .Values.haproxy.limits.cpu }}
              memory: {{ .Values.haproxy.limits.memory }}
        - name: controller
          image: {{ .Values.controller.image }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef: 
                  fieldPath: status.podIP
            - name: PGDATABASE 
              value: {{ .Values.dbName }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-passwords
                  key: CONTROLLER_USER_PASSWORD
          args: 
            - --time-step={{ .Values.controller.timeStep }}
            - --management-port=80
            - --promote-trigger-file=/shared/promote
            - --master-service={{ .Values.masterService }}
            - --pod-ip=$(POD_IP)
            - --db-port={{ .Values.dbPort }}
          volumeMounts:
            - name: shared
              mountPath: /shared
          readinessProbe:
            httpGet:
              port: 80
              path: /controller/ready
            failureThreshold: 1
          resources:
            limits:
              cpu: {{ .Values.controller.limits.cpu }}
              memory: {{ .Values.controller.limits.memory }}
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
        {{- if .Values.postgres.storage.className }}
        {{- if eq "-" .Values.postgres.storage.className }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.postgres.storage.className }}"
        {{- end }}
        {{- end }}