kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: consul
spec:
  replicas: {{ .Values.server.clusterSize }}
  selector:
    matchLabels:
      app: consul
  serviceName: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm: 
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: consul
      containers:
        - name: consul
          image: {{ .Values.image }}
          args: 
            - agent 
            - -server
            - -retry-join={{ .Values.server.service }}
            - -bootstrap-expect={{ .Values.server.clusterSize }}
            - -client=0.0.0.0
          volumeMounts:
            - name: data
              mountPath: /consul/data
          livenessProbe:
            exec:
              command: ['consul', 'members']
{{- if .Values.server.livenessProbe }}
{{ toYaml .Values.server.livenessProbe | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.server.resources | indent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- with .Values.server.storage }}
        resources:
          requests:
            storage: {{ .size }}
        {{- if .className }}
        {{- if eq "-" .className }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .className }}
        {{- end }}
        {{- end }}
        {{- end }}