kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: consul
spec:
  replicas: {{ .Values.server.clusterSize }}
  selector:
    matchLabels:
      app: consul
  serviceName: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm: 
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: consul
      containers:
        - name: consul
          image: {{ .Values.image }}
          args: 
            - agent 
            - -server
            - -retry-join={{ .Values.server.service }}
            - -bootstrap-expect={{ .Values.server.clusterSize }}
            - -client=0.0.0.0
          volumeMounts:
            - name: data
              mountPath: /consul/data
          readinessProbe:
            exec:
              command: ['/bin/sh', '-c', 'consul members -status=alive | grep $(hostname)']
          livenessProbe:
            exec:
              command: ['/bin/sh', '-c', 'consul members -status=alive | grep $(hostname)']
            initialDelaySeconds: 60
          resources:
            limits:
              cpu: {{ .Values.server.limits.cpu }}
              memory: {{ .Values.server.limits.memory }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.server.storage.size }}
        {{- if .Values.server.storage.className }}
        {{- if eq "-" .Values.server.storage.className }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.server.storage.className }}"
        {{- end }}
        {{- end }}