kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.postgres.masterService }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: tcp
---
kind: Endpoints
apiVersion: v1
metadata:
  name: postgres-master
