kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: postgres
spec: 
  replicas: {{ .Values.clusterSize }}
  selector: 
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image.name }}:{{ .Values.postgres.image.tag }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.dbName }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.superuserName }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-passwords
                  key: superuser
            - name: REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-passwords
                  key: replication
            - name: CONTROLLER_MANAGEMENT_PORT
              value: "80"
          livenessProbe:
            exec:
              command: ["/liveness-probe.sh"]
            initialDelaySeconds: 10
            failureThreshold: 1
        - name: consul
          image: {{ .Values.consul.image.name }}:{{ .Values.consul.image.tag }}
          args: ["agent", "-retry-join", {{ .Values.consul.serverHostName | quote }}]
        - name: controller
          image: {{ .Values.controller.image.name }}:{{ .Values.controller.image.tag }}
          args: 
            - --time-step=10
            - --management-port=80
            - --health-check-db={{ .Values.postgres.dbName }}
            - --health-check-db-user=monitoring
          readinessProbe:
            httpGet:
              port: 80
              path: /controller/ready
            failureThreshold: 1
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        {{- if .Values.storageClassName }}
        {{- if eq "-" .Values.storageClassName }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.storageClassName }}"
        {{- end }}
        {{- end }}