kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: postgres
spec: 
  replicas: {{ .Values.postgres.clusterSize }}
  updateStrategy:
    type: OnDelete
  selector: 
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: postgres
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm: 
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: postgres
      initContainers:
        - name: wait-consul-cluster
          image: alpine:latest
          command:
            - sh
            - -cx
            - |
              while [ $(nslookup {{ .Values.consul.serverService }} 2> /dev/null | grep -c "Address [0-9]:") -ne {{ .Values.consul.clusterSize }} ]; do
                sleep 3s
              done 
      volumes:
        - name: shared
          emptyDir: {}
        - name: haproxy-config
          configMap:
            name: haproxy-config
      containers:
        - name: postgres
          image: {{ .Values.postgres.image.name }}:{{ .Values.postgres.image.tag }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: shared
              mountPath: /shared
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.dbName }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.superuserName }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-passwords
                  key: superuser
            - name: REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-passwords
                  key: replication
            - name: POSTGRES_MASTER
              value: {{ .Values.postgres.masterService }}
            - name: CONTROLLER_MANAGEMENT_PORT
              value: "80"
            - name: PROMOTE_TRIGGER_FILE
              value: /shared/promote
          livenessProbe:
            exec:
              command: ["/liveness-probe.sh"]
            initialDelaySeconds: 30
            failureThreshold: 1
        - name: consul
          image: {{ .Values.consul.image.name }}:{{ .Values.consul.image.tag }}
          args: ["agent", "-retry-join", {{ .Values.consul.serverService | quote }}]
        - name: haproxy
          image: {{ .Values.haproxy.image.name }}:{{ .Values.haproxy.image.tag }}
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy
          ports:
            - name: tcp
              containerPort: 5433
        - name: controller
          image: {{ .Values.controller.image.name }}:{{ .Values.controller.image.tag }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef: 
                  fieldPath: status.podIP
          args: 
            - --time-step=10
            - --management-port=80
            - --health-check-db={{ .Values.postgres.dbName }}
            - --health-check-db-user=monitoring
            - --promote-trigger-file=/shared/promote
            - --master-service={{ .Values.postgres.masterService }}
            - --pod-ip=$(POD_IP)
          volumeMounts:
            - name: shared
              mountPath: /shared
          readinessProbe:
            httpGet:
              port: 80
              path: /controller/ready
            failureThreshold: 1
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        {{- if .Values.storageClassName }}
        {{- if eq "-" .Values.storageClassName }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.storageClassName }}"
        {{- end }}
        {{- end }}